name: fisma_inso2
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  flutter_map: ^5.0.0
  latlong2: ^0.9.1
  json_annotation: ^4.8.0
  pdf: ^3.8.4
  share_plus: ^10.0.2
  validators: ^3.0.0
  universal_html: ^2.2.4
  shared_preferences: ^2.3.2
  flutter_local_notifications: ^17.2.2
  printing: ^5.13.2
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.7.0 # Asegúrate de usar una versión compatible

flutter:
  assets:
    - assets/logo.png
    - assets/fondo.jpg
    - assets/jujuy.jpg

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
  uses-material-design: true
