name: fisma_inso2
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  cupertino_icons: ^1.0.6
  flutter_map: ^5.0.0
  latlong2: ^0.9.1
  mapbox_gl: ^0.16.0
  path_provider: ^2.0.11
  json_annotation: ^4.8.0
  pdf: ^3.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.1.11
  json_serializable: ^6.7.0 # Asegúrate de usar una versión compatible

flutter:
  assets:
    - assets/logo_fisma_sf.png
    - assets/fondo.jpg
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
  uses-material-design: true
